name: Markdown Linting

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Markdown Lint
        uses: gaurav-nelson/github-action-markdown-lint@v1
